/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/scala_plugin.html
 */

plugins {
    // Apply the scala plugin to add support for Scala
    scala
    groovy
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven { url = uri("https://repo.jenkins-ci.org/releases/") }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType<Test> {
    //useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

sourceSets {
    main {
        withConvention(ScalaSourceSet::class) {
            scala {
                setSrcDirs(listOf("src"))
            }
        }
        withConvention(GroovySourceSet::class) {
            groovy {
                setSrcDirs(listOf("src"))
            }
        }
    }
    test {
        withConvention(ScalaSourceSet::class) {
            scala {
                setSrcDirs(listOf("test/scala"))
            }
        }
        resources.srcDir(file("test/resources"))
    }
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.codehaus.groovy:groovy-all:3.0.5")
    implementation("org.scala-lang:scala-library:2.13.3")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.13")
    testImplementation("org.scalatest:scalatest_2.13:3.2.2")
    testImplementation("org.scalatestplus:junit-4-13_2.13:3.2.2.0")
    testImplementation("com.lesfurets:jenkins-pipeline-unit:1.7")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.13:1.2.0")
}
